name: py27
dependencies:
- decorator=3.4.0=py27_0
- networkx=1.9.1=py27_0
- openssl=1.0.1k=1
- pip=6.1.1=py27_0
- python=2.7.9=1
- readline=6.2=2
- setuptools=16.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- zlib=1.2.8=0
- pip:
  - aniso8601==1.0.0
  - click==4.0
  - execnet==1.3.0
  - flask==0.10.1
  - flask-restful==0.3.2
  - itsdangerous==0.24
  - jinja2==2.7.3
  - markupsafe==0.23
  - pep8==1.6.2
  - py==1.4.27
  - py2cytoscape==0.3.4
  - pytest==2.7.1
  - pytest-cache==1.0
  - pytest-pep8==1.0.6
  - pytz==2015.4
  - redis==2.10.3
  - rq==0.5.2
  - six==1.9.0
  - werkzeug==0.10.4

