# Cytoscape CI sample setup
# 
# Rev 2
# by Keiichiro Ono
#

# Redis server: for job management
redis:
  image: redis
  ports:
    - "6379:6379"

# REST API server using Flask
service:
  build: ciservice
  # Remove "volumes" section when you deploy this
  # to the production server.
  # volumes:
  #   - ciservice:/api
  links:
    - redis
    - collector
    - dataserver
    - resultserver
    - kernelserver
  ports:
    - "80:5000" # REST API for users
    - "5556:5556"
    - "8888:8888"
    - "9999:9999" # endpoint registration

# Python workers sample
workers:
  build: workers/pyworker
  links:
    - service
    - collector
    - redis
    - dataserver
    - resultserver
    - kernelserver

#workers2:
#  build: workers/python2
#  links:
#    - service
#    - collector
#    - dataserver

# Workers with R/Bioconductor
#rworkers:
#  build: workers/r
#  links:
#    - service
#    - collector

# Colector /
collector:
  build: collector
  # volumes:
  #   - collector:/collector
  links:
    - redis
    - resultserver
  ports:
    - "5558:5558"
    - "6666:6666"
    - "5001:5001" # for Flask


# For input data caching
dataserver:
  build: file-server
  links:
    - redis
  ports:
    - "3000:3000"


# For result data caching
resultserver:
  build: file-server
  links:
    - redis
  ports:
    - "3001:3000"

kernelserver:
  build: file-server
  links:
    - redis
  ports:
    - "3333:3000"


# Frontend to test CI
#notebook:
#  image: idekerlab/vizbi-2015
#  ports:
#    - "8080:8888"
#  volumes:
#    - sample-notebooks:/notebooks
#  environment:
#    - PASSWORD=citest
#    - USE_HTTP=1
