redis:
  image: redis
  ports:
    - "6379:6379"


service:
  build: ciservice
  # Remove "volumes" section when you deploy this
  # to the production server.
  volumes:
    - ciservice:/api
  links:
    - redis
  ports:
    - "80:5000"

collector:
  build: router

workers:
  build: workers/python
  links:
    - service
    - collector
