redis:
  image: redis
  ports:
    - "6379:6379"


service:
  build: ciservice
  # Remove "volumes" section when you deploy this
  # to the production server.
  volumes:
    - ciservice:/api
  links:
    - redis
    - collector
  ports:
    - "80:5000"
    - "5556:5556"
    - "8888:8888"


workers:
  build: workers/python
  links:
    - service
    - collector

rworkers:
  build: workers/r
  links:
    - service
    - collector

collector:
  build: collector
  volumes:
    - collector:/collector
  links:
    - redis
  ports:
    - "5558:5558"
    - "6666:6666"
