# Sample worker definition: HelloWorker

hello:
  endpoint: hello-java
  description: Sample Java worker to display greeting message
  worker: org.cytoscape.ci.worker.HelloWorker
  instances: 3
  servers:
    task_queue:
      location: service
      port: 5560
    collector:
      location: collector
      port: 5558
    monitor:
      location: collector
      port: 6666
    redis:
      location: redis
      port: 6379
    result:
      location: resultserver
      port: 3000
    datacache:
      location: dataserver
      port: 3000
  parameters:
    - name: message
      type: string
      description: Greeting message
      required: true
